### ISSUE TITLE
Script won't run - logs attached

### ISSUE THREAD

**Issue by Manchovies** [calyptis/MusicSync#1]
To the best of my knowledge, I've followed all the instructions to a T. I did have to manually install spotipy. But here's what I'm getting when I try: 

sonic@SpencerPC MINGW64 /c/MusicSync/MusicSync (master)
$ python src/main.py
2023-08-20 10:00:27,834 [INFO] Parsing Apple Music library
==============
C:\MusicSync\MusicSync\src\apple_music\library.py:101: DtypeWarning: Columns (18,20,25,27,44,62,63) have mixed types. Specify dtype option on import or set low_memory=False.
  apple_music_songs = pd.read_csv(in_song_file).set_index("Track ID")
Traceback (most recent call last):
  File "C:\Users\sonic\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 146, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index_class_helper.pxi", line 49, in pandas._libs.index.Int64Engine._check_type
KeyError: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\MusicSync\MusicSync\src\main.py", line 21, in <module>
    prepare_playlists()
  File "C:\MusicSync\MusicSync\src\apple_music\library.py", line 103, in prepare_playlists
    parsed_playlists = {
  File "C:\MusicSync\MusicSync\src\apple_music\library.py", line 104, in <dictcomp>
    k: list(apple_music_songs.loc[v, ["Name", "Artist", "Album"]].apply(tuple, axis=1).values)
  File "C:\Users\sonic\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexing.py", line 1067, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\sonic\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexing.py", line 1247, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\sonic\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexing.py", line 967, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "C:\Users\sonic\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexing.py", line 1312, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\Users\sonic\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexing.py", line 1260, in _get_label
    return self.obj.xs(label, axis=axis)
  File "C:\Users\sonic\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py", line 4056, in xs
    loc = index.get_loc(key)
  File "C:\Users\sonic\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: None

sonic@SpencerPC MINGW64 /c/MusicSync/MusicSync (master)
$ python src/apple_music/library.py
C:\MusicSync\MusicSync\src\apple_music\library.py:101: DtypeWarning: Columns (18,20,25,27,44,62,63) have mixed types. Specify dtype option on import or set low_memory=False.
  apple_music_songs = pd.read_csv(in_song_file).set_index("Track ID")
Traceback (most recent call last):
  File "C:\Users\sonic\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 146, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index_class_helper.pxi", line 49, in pandas._libs.index.Int64Engine._check_type
KeyError: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\MusicSync\MusicSync\src\apple_music\library.py", line 126, in <module>
    prepare_playlists()
  File "C:\MusicSync\MusicSync\src\apple_music\library.py", line 103, in prepare_playlists
    parsed_playlists = {
  File "C:\MusicSync\MusicSync\src\apple_music\library.py", line 104, in <dictcomp>
    k: list(apple_music_songs.loc[v, ["Name", "Artist", "Album"]].apply(tuple, axis=1).values)
  File "C:\Users\sonic\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexing.py", line 1067, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\sonic\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexing.py", line 1247, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\sonic\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexing.py", line 967, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "C:\Users\sonic\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexing.py", line 1312, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\Users\sonic\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexing.py", line 1260, in _get_label
    return self.obj.xs(label, axis=axis)
  File "C:\Users\sonic\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\generic.py", line 4056, in xs
    loc = index.get_loc(key)
  File "C:\Users\sonic\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: None

**Comment by calyptis** [comment]
Hi @Manchovies, thanks for trying out MusicSync and for opening an issue.
I tested the library only on Mac OS. It seems like the most plausible cause is that `Library.xml` is not parsed properly.
More specifically, it seems like the column `Track ID` contains `NaN`s.
Could you please verify that this is indeed the case in both the generated CSV file (`data/apple_music/songs.csv`) and the original XML file (`data/apple_music/Library.xml`)?

**Comment by suwudo** [comment]
Hello, I have encountered the same issue, but with MacOS

After reviewing your comment, I popped the CSV file into each Excel and VSCode and I cannot find any non-numerical values in the "Track ID" column. It also shows me roughly the same amount of rows as there are songs in my Apple Music Library. I did take a peak into the XML, and I didn't see any. However I can't find an efficient way to confirm completely.

```username@MacBook-Pro MusicSync % python3 -m src.main
2024-01-18 14:36:57,753 [INFO] Parsing Apple Music library
==============
/Users/username/Documents/GitHub/MusicSync/src/apple_music/library.py:101: DtypeWarning: Columns (48,55,59,62) have mixed types. Specify dtype option on import or set low_memory=False.
  apple_music_songs = pd.read_csv(in_song_file).set_index("Track ID")
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 160, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index_class_helper.pxi", line 70, in pandas._libs.index.Int64Engine._check_type
KeyError: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/username/Documents/GitHub/MusicSync/src/main.py", line 21, in <module>
    prepare_playlists()
  File "/Users/username/Documents/GitHub/MusicSync/src/apple_music/library.py", line 104, in prepare_playlists
    k: list(apple_music_songs.loc[v, ["Name", "Artist", "Album"]].apply(tuple, axis=1).values)
            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/indexing.py", line 1147, in __getitem__
    return self._getitem_tuple(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/indexing.py", line 1330, in _getitem_tuple
    return self._getitem_lowerdim(tup)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/indexing.py", line 1039, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/indexing.py", line 1393, in _getitem_axis
    return self._get_label(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/indexing.py", line 1343, in _get_label
    return self.obj.xs(label, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/generic.py", line 4236, in xs
    loc = index.get_loc(key)
          ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: None
```

Because the error seems to happen in the in `apple_music/library.py` in `def prepare_playlists`, I deleted all the playlists from my XML file just to get my library transferred to spotify.

This is the error I'm prompted with now. Despite the "Sync to Spotify" message, nothing seems to have happened before the operation ends. I cannot figure out a way around it. 

```
username@MacBook-Pro MusicSync % python3 -m src.main
2024-01-18 16:05:45,670 [INFO] Parsing Apple Music library
==============
/Users/username/Documents/GitHub/MusicSync/src/apple_music/library.py:101: DtypeWarning: Columns (48,55,59,62) have mixed types. Specify dtype option on import or set low_memory=False.
  apple_music_songs = pd.read_csv(in_song_file).set_index("Track ID")
2024-01-18 16:05:59,446 [INFO] Sync to Spotify
==============
username@MacBook-Pro MusicSync % 
```

**Comment by calyptis** [comment]
Thanks for reaching out.

Regarding "Sync to Spotify" message but no syncing taking place, is your `PREPARED_PLAYLIST_FILE` file empty? If there are no playlists, "Sync to Spotify" is being logged but then the for loop iterates on an empty dictionary, hence no syncing.

Regarding the `KeyError`, perhaps one check you could run is 

`pd.read_csv(SONG_FILE)["Track ID"].isnull().sum()`

I suspect this returns non-zero. Another check to run is to see if some values are non-digits, try:

```
df = pd.read_csv(SONG_FILE)
mask = df["Track ID"].astype(str).apply(lambda x: x.isdigit())
df.loc[~mask, "Track ID"].head()
```

**Comment by suwudo** [comment]
Hey! Thanks for the quick response.

By `PREPARED_PLAYLIST_FILE` you mean the `parsed_playlists.json`? Yea, It's empty aside from `{}`

I went ahead and put your feedback into `library.py: def prepare_playlists`. Here's what I have and the output.

library.py:
```
def prepare_playlists(
        in_song_file: str = SONG_FILE,
        in_playlist_file: str = RAW_PLAYLIST_FILE,
        out_playlist_file: str = PREPARED_PLAYLIST_FILE
):
    """
    Transforms the raw playlist file into a playlist file that contains
    a song's name, artist and album.
    This information is then used to create a query to Spotify's API when syncing playlists.

    Returns
    -------
    """
101 # apple_music_songs = pd.read_csv(in_song_file, usecols = [0,1,2,3,4,5,6]).set_index("Track ID")

    # Troubleshooting
104 apple_music_songs = pd.read_csv(SONG_FILE)["Track ID"].isnull().sum()
105 df = pd.read_csv(SONG_FILE)
    mask = df["Track ID"].astype(str).apply(lambda x: x.isdigit())
    df.loc[~mask, "Track ID"].head()

    apple_music_playlists = json.load(open(in_playlist_file, "rb"))
    parsed_playlists = {
        k: list(apple_music_songs.loc[v, ["Name", "Artist", "Album"]].apply(tuple, axis=1).values)
        for k, v in apple_music_playlists.items()
    }
    json.dump(parsed_playlists, open(out_playlist_file, "w"))
```

Terminal:
```
username@MacBook-Pro-207 MusicSync % python3 -m src.main
2024-01-21 16:03:55,089 [INFO] Parsing Apple Music library
==============
/Users/username/Documents/GitHub/MusicSync/src/apple_music/library.py:104: DtypeWarning: Columns (48,55,59,62) have mixed types. Specify dtype option on import or set low_memory=False.
  apple_music_songs = pd.read_csv(in_song_file)["Track ID"].isnull().sum()
/Users/username/Documents/GitHub/MusicSync/src/apple_music/library.py:105: DtypeWarning: Columns (48,55,59,62) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(in_song_file)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/username/Documents/GitHub/MusicSync/src/main.py", line 21, in <module>
    prepare_playlists()
  File "/Users/username/Documents/GitHub/MusicSync/src/apple_music/library.py", line 111, in prepare_playlists
    k: list(apple_music_songs.loc[v, ["Name", "Artist", "Album"]].apply(tuple, axis=1).values)
            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'numpy.int64' object has no attribute 'loc'
```

I used RainbowCSV in VSCode to investigate these problematic columns `Columns (48,55,59,62)` and here's what I found:

48: Protected
55: Album Rating Computed
59: Playlist Only
62: Movement Count

I opened the CSV in Excel to see what information lies here for the tracks that use it, and I found that `Movement Count` corresponds to a few classical tracks in the library. I was able to Cmnd + Downkey in that column to see a numerical value for some tracks.  I am guessing that songs that are found with `Playlist Only` corresponds to Apple Music/Curated playlists, and I'm unsure what `Album Rating Computed` or `Protected` relate to. There was no information in these columns that Excel displayed.

I assume these columns and their values are what is effecting the script. I'll admit, I'm actually pretty novice when it comes to python, but I wonder if the solution would be to omit all the information beyond column 6 or 7. Those columns do not seem to be functionally useful to how the program is supposed to run.

I hope this information helps.

**Comment by calyptis** [comment]
So `apple_music_songs` is a float for you since you define it as `apple_music_songs = pd.read_csv(SONG_FILE)["Track ID"].isnull().sum()`, hence the `AttributeError` as `.loc` works for pandas series.

I have made some modifications to `library.py`. Specifically, it will print out how many track IDs are not valid digits.
Please pull the new version of the repo and try again.
You should get 

```
>>> python -m src.apple_music.library
[OUT] Number of invalid track IDs: 0
```

Also, please make sure your `RAW_PLAYLIST_FILE` is not empty. You need to have at least one playlist defined in your Apple Music Library, which preferably should contain songs in your library (i.e. not Apple Music managed playlists). As my code only syncs playlists.
